/* ============================================================
   PROJECTS — edit all case study content here

   Each entry:
     file      — filename in images/ (card thumbnail)
     client    — client name
     title     — project title (also generates the URL slug)
     cat       — short category label (optional)
     overview  — lead paragraph for the case study
     challenge — brief, constraints, or problem space
     approach  — creative or strategic approach taken
     outcome   — results, impact, or what was delivered
     images    — array of image paths shown as a gallery below the text
============================================================ */

function toSlug(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export const PROJECTS = [
  {
    file:      'index-addiction.jpg',
    client:    'Centre for Motivation and Change',
    title:     'Addiction. The Next Step',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-backstory.jpg',
    client:    'APTN / Mooswa Films',
    title:     'Backstory',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-bchydro.jpg',
    client:    'BC Hydro',
    title:     'History Revealed',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-capturingreality.jpg',
    client:    'National Film Board of Canada',
    title:     'Capturing Reality',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-cbc-vancouver.jpg',
    client:    'CBC Vancouver / Rethink',
    title:     "Vancouver's Talking",
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-food-for-thought.jpg',
    client:    'APTN / Mooswa Films',
    title:     'Food for Thought',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-foran.jpg',
    client:    'Foran Mining',
    title:     'Net Positive',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-frontier.jpg',
    client:    'Discovery / Netflix',
    title:     'Frontier Dark Providence',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-hunting-in-canada.jpg',
    client:    'APTN / Mooswa Films',
    title:     'Hunting in Canada',
    casestudy: false,
    cat:       'Editorial',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-kennys.jpg',
    client:    'Documentary / Relevision',
    title:     "Kenny's Jazz Pad",
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-legacies150.jpg',
    client:    'National Film Board of Canada',
    title:     'Legacies 150',
    casestudy: false,
    cat:       'Brand Strategy',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-myrefugeeclaim.jpg',
    client:    'Kinbrace / UNHCR',
    title:     'My Refugee Claim',
    casestudy: true,
    cat:       'Digital Product',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-nar.jpg',
    client:    'APTN / Realworld Media',
    title:     'Northern Air Rescue',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-nativeplanet.jpg',
    client:    'APTN / Realworld Media',
    title:     'Native Planet',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-pinepoint.jpg',
    client:    'National Film Board of Canada',
    title:     'Pinepoint',
    casestudy: false,
    cat:       'Data Story',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-powertogive.jpg',
    client:    'Power to Give Foundation',
    title:     'Philanthropy Reimagined',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-powertothepeople.jpg',
    client:    'APTN / Realworld Media',
    title:     'Power to the People',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-reelcanada.jpg',
    client:    'Reel Canada',
    title:     'A World of Canadian Film',
    casestudy: true,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-similkameen.jpg',
    client:    'National Film Board',
    title:     'Similkameen Crossroads',
    casestudy: false,
    cat:       'Environmental',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-smashball.jpg',
    client:    'Volleyball Canada',
    title:     'Smashball Trainer',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-stashing-their-cash.jpg',
    client:    'CBC News',
    title:     'Stashing Their Cash',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-the-conversation.jpg',
    client:    'Telus / FNHA / Realworld Media',
    title:     'The Conversation',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-the-hub.jpg',
    client:    'Centre for Civic Engagement',
    title:     'The Hub',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-truth-and-lies.jpg',
    client:    'CBC News',
    title:     'Truth and Lies',
    casestudy: false,
    cat:       'Editorial',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-uninterrupted.jpg',
    client:    'Canada Wild Productions / Agentic',
    title:     'Uninterrupted',
    casestudy: false,
    cat:       '',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
  {
    file:      'index-waterworlds.jpg',
    client:    'APTN / Water Worlds Productions',
    title:     'Water Worlds',
    casestudy: false,
    cat:       'Environmental',
    overview:  '',
    challenge: '',
    approach:  '',
    outcome:   '',
    images:    [],
  },
].map(p => ({ ...p, src: 'images/' + p.file, slug: toSlug(p.title) }));
