/* ============================================================
   PROJECTS — edit all case study content here

   Each entry:
     file      — filename in assets/ (card thumbnail)
     client    — client name
     title     — project title (also generates the URL slug)
     year      — year the project was completed
     casestudy — true if a matching case-studies/<slug>.js exists
     cat       — short category label (optional)
     accentColourPrimary   — primary accent colour for this project (hex)
     textColour — secondary accent colour for this project (hex)
============================================================ */

function toSlug(title) {
  return title.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

export const PROJECTS = [
  {
    file:      'index-addiction.jpg',
    client:    'Center for Motivation and Change',
    title:     'Addiction. The Next Step',
    year:      '2017',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#2a2e3b',
    textColour: 'light',
  },
  {
    file:      'index-backstory.jpg',
    client:    'APTN / Mooswa Films',
    title:     'The Backstory of Art & Dan',
    year:      '2017',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#e36d3f',
    textColour: 'light',
  },
  {
    file:      'index-bchydro.jpg',
    client:    'BC Hydro',
    title:     'History Revealed',
    year:      '2021',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#912816',
    textColour: 'light',
  },
  {
    file:      'index-capturingreality.jpg',
    client:    'National Film Board of Canada',
    title:     'Capturing Reality',
    year:      '2014',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#dfa421',
    textColour: 'dark',
  },
  {
    file:      'index-cbc-vancouver.jpg',
    client:    'CBC Vancouver / Rethink',
    title:     "Vancouver’s Talking",
    year:      '2018',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#76b7da',
    textColour: 'dark',
  },
  {
    file:      'index-food-for-thought.jpg',
    client:    'APTN / Mooswa Films',
    title:     'Food for Thought',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-foran.jpg',
    client:    'Foran Mining',
    title:     'Net Positive',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-frontier.jpg',
    client:    'Discovery / Netflix',
    title:     'Frontier Dark Providence',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-hunting-in-canada.jpg',
    client:    'APTN / Mooswa Films',
    title:     'Hunting in Canada',
    year:      '',
    casestudy: false,
    cat:       'Editorial',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-kennys.jpg',
    client:    'Documentary / Relevision',
    title:     "Kenny's Jazz Pad",
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-legacies150.jpg',
    client:    'National Film Board of Canada',
    title:     'Legacies 150',
    year:      '',
    casestudy: false,
    cat:       'Brand Strategy',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-myrefugeeclaim.jpg',
    client:    'Kinbrace / UNHCR',
    title:     'My Refugee Claim',
    year:      '',
    casestudy: true,
    cat:       'Digital Product',
    accentColourPrimary:   '#709093',
    textColour: 'light',
  },
  {
    file:      'index-nar.jpg',
    client:    'APTN / Realworld Media',
    title:     'Northern Air Rescue',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-nativeplanet.jpg',
    client:    'APTN / Realworld Media',
    title:     'Native Planet',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-pinepoint.jpg',
    client:    'National Film Board of Canada',
    title:     'Pinepoint',
    year:      '',
    casestudy: false,
    cat:       'Data Story',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-powertogive.jpg',
    client:    'Power to Give Foundation',
    title:     'Philanthropy Reimagined',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-powertothepeople.jpg',
    client:    'APTN / Realworld Media',
    title:     'Power to the People',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-reelcanada.jpg',
    client:    'Reel Canada',
    title:     'A World of Canadian Film',
    year:      '2023',
    casestudy: true,
    cat:       '',
    accentColourPrimary:   '#042C56',
    textColour: 'light',
  },
  {
    file:      'index-similkameen.jpg',
    client:    'National Film Board',
    title:     'Similkameen Crossroads',
    year:      '',
    casestudy: false,
    cat:       'Environmental',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-smashball.jpg',
    client:    'Volleyball Canada',
    title:     'Smashball Trainer',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-stashing-their-cash.jpg',
    client:    'CBC News',
    title:     'Stashing Their Cash',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-the-conversation.jpg',
    client:    'Telus / FNHA / Realworld Media',
    title:     'The Conversation',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-the-hub.jpg',
    client:    'Centre for Civic Engagement',
    title:     'The Hub',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-truth-and-lies.jpg',
    client:    'CBC News',
    title:     'Truth and Lies',
    year:      '',
    casestudy: false,
    cat:       'Editorial',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-uninterrupted.jpg',
    client:    'Canada Wild Productions / Agentic',
    title:     'Uninterrupted',
    year:      '',
    casestudy: false,
    cat:       '',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
  {
    file:      'index-waterworlds.jpg',
    client:    'APTN / Water Worlds Productions',
    title:     'Water Worlds',
    year:      '',
    casestudy: false,
    cat:       'Environmental',
    accentColourPrimary:   '#ffffff',
    textColour: 'light',
  },
].map(p => ({ ...p, src: 'assets/' + p.file, slug: toSlug(p.title) }));
